version: '3.8'

services:
  tgbot:
    build: ./
    restart: unless-stopped

  my-mongo:
    image: mongo:8.0
    ports:
      - "27017:27017"
    networks:
      - my-network
    restart: unless-stopped

networks:
  my-network:
    driver: bridge